services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: mobility
      POSTGRES_USER: mobility
      POSTGRES_PASSWORD: mobility
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres:/docker-entrypoint-initdb.d:ro
